version: '2'
services:
  postgresql:
    image: postgres:9.5
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  web_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    links:
      - postgresql
      - elastic
      - influxdb
    volumes:
      - ./data/ucrm:/data
    ports:
      - 8080:80
      - 8081:81
      - 8443:443
    command: "server"

  elastic:
    image: elasticsearch:2
    restart: always

  influxdb:
    image: influxdb:0.13-alpine
    restart: always
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  sync_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./data/ucrm:/data
    links:
      - postgresql
    command: "sync"

  crm_invoice_send_email_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./data/ucrm:/data
    links:
      - postgresql
    command: "crm_invoice_send_email"

  crm_draft_approve_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./data/ucrm:/data
    links:
      - postgresql
    command: "crm_draft_approve"

  crm_netflow:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./data/ucrm:/data
    links:
      - postgresql
      - influxdb
    ports:
      - 2055:2055/udp
    command: "crm_netflow"

  crm_ping:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./data/ucrm:/data
    links:
      - postgresql
      - influxdb
    command: "crm_ping"

  crm_search_devices_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./data/ucrm:/data
    links:
      - postgresql
    command: "crm_search_devices"
