version: '2'
services:
  postgresql:
    image: postgres:9.5
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    links:
      - postgresql
      - elastic
      - rabbitmq
    volumes:
      - ./data/ucrm:/data
    ports:
      - 8080:80
      - 8081:81
      - 8443:443
    command: "server"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  elastic:
    image: elasticsearch:2
    restart: always
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  rabbitmq:
    image: rabbitmq:3
    restart: always
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  supervisord:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./data/ucrm:/data
    links:
      - postgresql
      - elastic
      - rabbitmq
    command: "supervisord"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  sync_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./data/ucrm:/data
    links:
      - postgresql
      - elastic
      - rabbitmq
    command: "sync"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  crm_search_devices_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./data/ucrm:/data
    links:
      - postgresql
      - elastic
      - rabbitmq
    command: "crm_search_devices"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  crm_netflow_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./data/ucrm:/data
    links:
      - postgresql
      - elastic
      - rabbitmq
    ports:
      - 2055:2055/udp
    command: "crm_netflow"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  crm_ping_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    volumes:
      - ./data/ucrm:/data
    links:
      - postgresql
      - elastic
      - rabbitmq
    command: "crm_ping"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
